

set number
set relativenumber
set tabstop=4
set shiftwidth=4
set expandtab
set autoindent
set smartindent
set wrap
"set cursorline
set incsearch
set ignorecase
set smartcase
set hlsearch
set showmatch
set wildmenu
syntax on
inoremap jk <Esc>
noremap  ; :


